In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
ab = pd.read_csv('D:\\My Work\\Dataset\\Fish.csv')

ab

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
ab.info

<bound method DataFrame.info of     Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]>

In [7]:
ab.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [8]:
ab.shape

(159, 7)

In [9]:
x = ab.iloc[ : , :-1].values
y = ab.iloc[ : , -1].values
print(x)
print(y)

[['Bream' 242.0 23.2 25.4 30.0 11.52]
 ['Bream' 290.0 24.0 26.3 31.2 12.48]
 ['Bream' 340.0 23.9 26.5 31.1 12.3778]
 ['Bream' 363.0 26.3 29.0 33.5 12.73]
 ['Bream' 430.0 26.5 29.0 34.0 12.444]
 ['Bream' 450.0 26.8 29.7 34.7 13.6024]
 ['Bream' 500.0 26.8 29.7 34.5 14.1795]
 ['Bream' 390.0 27.6 30.0 35.0 12.67]
 ['Bream' 450.0 27.6 30.0 35.1 14.0049]
 ['Bream' 500.0 28.5 30.7 36.2 14.2266]
 ['Bream' 475.0 28.4 31.0 36.2 14.2628]
 ['Bream' 500.0 28.7 31.0 36.2 14.3714]
 ['Bream' 500.0 29.1 31.5 36.4 13.7592]
 ['Bream' 340.0 29.5 32.0 37.3 13.9129]
 ['Bream' 600.0 29.4 32.0 37.2 14.9544]
 ['Bream' 600.0 29.4 32.0 37.2 15.437999999999999]
 ['Bream' 700.0 30.4 33.0 38.3 14.8604]
 ['Bream' 700.0 30.4 33.0 38.5 14.937999999999999]
 ['Bream' 610.0 30.9 33.5 38.6 15.633]
 ['Bream' 650.0 31.0 33.5 38.7 14.4738]
 ['Bream' 575.0 31.3 34.0 39.5 15.1285]
 ['Bream' 685.0 31.4 34.0 39.2 15.9936]
 ['Bream' 620.0 31.5 34.5 39.7 15.5227]
 ['Bream' 680.0 31.8 35.0 40.6 15.4686]
 ['Bream' 700.0 31.9 35.0 40

In [10]:
ab

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [11]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[1.0 0.0 0.0 ... 25.4 30.0 11.52]
 [1.0 0.0 0.0 ... 26.3 31.2 12.48]
 [1.0 0.0 0.0 ... 26.5 31.1 12.3778]
 ...
 [0.0 0.0 0.0 ... 13.0 13.8 2.2769999999999997]
 [0.0 0.0 0.0 ... 14.3 15.2 2.8728]
 [0.0 0.0 0.0 ... 15.0 16.2 2.9322]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
cd = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(cd.fit_transform(x))

In [15]:
print(x)

[[0.0 1.0 0.0 ... 25.4 30.0 11.52]
 [0.0 1.0 0.0 ... 26.3 31.2 12.48]
 [0.0 1.0 0.0 ... 26.5 31.1 12.3778]
 ...
 [1.0 0.0 0.0 ... 13.0 13.8 2.2769999999999997]
 [1.0 0.0 0.0 ... 14.3 15.2 2.8728]
 [1.0 0.0 0.0 ... 15.0 16.2 2.9322]]


In [16]:
print(type(x))

<class 'numpy.ndarray'>


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [18]:
x_test.shape

(32, 13)

In [19]:
x_train.shape

(127, 13)

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)


LinearRegression()

In [21]:
am = regressor.predict(x_test)

print(am)


[4.38279449 3.38339191 3.88402001 3.76583349 5.96668042 6.89927111
 6.58442579 4.02007325 6.93611506 3.59590466 3.46223608 4.79632112
 7.10072125 7.39434824 2.00004199 3.04268687 3.55898264 6.94110772
 3.76244959 5.97203357 2.00994396 5.25582111 3.72337595 7.62736022
 2.42744522 4.82327473 5.90333898 4.66318611 6.90514304 1.24892365
 5.24826435 3.54063573]
