# Reshape Function 

In [1]:
# Reshape function is used for change the dimension of array.

In [2]:
import numpy as ac
ar1=ac.array([65,77,45,67,34,56,23,45])
ar1.reshape(4,2)           ##(4=Rows,2=Columns)##

array([[65, 77],
       [45, 67],
       [34, 56],
       [23, 45]])

In [3]:
import numpy as ab
ar3=ab.array([5,6,7,8,9,4,5,3,34,56,23,67])
atp=ar3.reshape(2,3,2)        ##(2=Array Dimension,3=Rows,2=Columns)##     
print(atp)

[[[ 5  6]
  [ 7  8]
  [ 9  4]]

 [[ 5  3]
  [34 56]
  [23 67]]]


In [4]:
import numpy as np
ar1 = np.array([54,34,67,89,12,34,45,56])
print("Array dimension is::",ar1.ndim)
print("******************************************")
print("Original array::")
print(ar1)
print("******************************************")
print("After array reshape::")
print(ar1.reshape(8,1))
print("*******************************************")
print("8 is a size of row && 1 is size of cloumn")

Array dimension is:: 1
******************************************
Original array::
[54 34 67 89 12 34 45 56]
******************************************
After array reshape::
[[54]
 [34]
 [67]
 [89]
 [12]
 [34]
 [45]
 [56]]
*******************************************
8 is a size of row && 1 is size of cloumn


In [5]:
import numpy as np
ar1 = np.array([54,34,67,89,12,34,45,56])
print("Original array::")
print(ar1)
print("******************************************")
print("After array reshape::")
print(ar1.reshape(4,2))
print("*******************************************")
print("4 is a size of row && 2 is size of cloumn")

Original array::
[54 34 67 89 12 34 45 56]
******************************************
After array reshape::
[[54 34]
 [67 89]
 [12 34]
 [45 56]]
*******************************************
4 is a size of row && 2 is size of cloumn


In [6]:
import numpy as np
ar1 = np.array([[12,23,34,45],[56,67,78,98]])
ar2 = np.array([[32,43,65,87],[89,54,76,43]])
print("ar1 dimension is::",ar1.ndim)
print("ar2 dimension is::",ar2.ndim)
print("------------------------------")
print("original ar1 :")
print(ar1)
print("------------------------------")
print("original ar2 :")
print(ar2)
print("-----------------------------")
print("concatenate two array ar1 & ar2 :")
at1 = np.concatenate((ar1,ar2))
print(at1)
print("----------------------------------")
print("Rehsape the conatenate array::")
print(at1.reshape(16,1))


ar1 dimension is:: 2
ar2 dimension is:: 2
------------------------------
original ar1 :
[[12 23 34 45]
 [56 67 78 98]]
------------------------------
original ar2 :
[[32 43 65 87]
 [89 54 76 43]]
-----------------------------
concatenate two array ar1 & ar2 :
[[12 23 34 45]
 [56 67 78 98]
 [32 43 65 87]
 [89 54 76 43]]
----------------------------------
Rehsape the conatenate array::
[[12]
 [23]
 [34]
 [45]
 [56]
 [67]
 [78]
 [98]
 [32]
 [43]
 [65]
 [87]
 [89]
 [54]
 [76]
 [43]]


# Split Function

In [7]:
# Split function is used for one array is split into two/more array. 

In [8]:
import numpy as np
ar2=np.array([22,23,24,25,62,72])
print("original array::")
print(ar2)
print("-----------------------------")
print("After the spliting array::")
ap=np.array_split(ar2,3)
print(ap)

original array::
[22 23 24 25 62 72]
-----------------------------
After the spliting array::
[array([22, 23]), array([24, 25]), array([62, 72])]


In [9]:
import numpy as np
ar1 = np.array([9,8,7,6,10,11,12,13])
print("original array::")
print(ar1)
print("------------------------------")
print("array dimension::",ar1.ndim)
print("-----------------------------")
print("After spliting array::")
arr = np.array_split(ar1,8)                # 8=array spliting size
print(arr)

original array::
[ 9  8  7  6 10 11 12 13]
------------------------------
array dimension:: 1
-----------------------------
After spliting array::
[array([9]), array([8]), array([7]), array([6]), array([10]), array([11]), array([12]), array([13])]


In [10]:
import numpy as np
ar1 = np.array([[23,21,12,43],[97,34,54,65]])
ar2 = np.array([[87,32,23,12],[66,45,32,78]])
print("original ar1 ::")
print(ar1)
print("-------------------------------")
print("ar1 dimension is ::",ar1.ndim)
print("-------------------------------")
print("after spliting ar1 ::")
arr1 = np.array_split(ar1,5)
print(arr1)
print("***************************************")
print("***************************************")

print("original ar2 ::")
print(ar2)
print("-------------------------------")
print("ar1 dimension is ::",ar2.ndim)
print("-------------------------------")
print("after spliting ar2 ::")
arr2 = np.array_split(ar2,5)
arr2

original ar1 ::
[[23 21 12 43]
 [97 34 54 65]]
-------------------------------
ar1 dimension is :: 2
-------------------------------
after spliting ar1 ::
[array([[23, 21, 12, 43]]), array([[97, 34, 54, 65]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]
***************************************
***************************************
original ar2 ::
[[87 32 23 12]
 [66 45 32 78]]
-------------------------------
ar1 dimension is :: 2
-------------------------------
after spliting ar2 ::


[array([[87, 32, 23, 12]]),
 array([[66, 45, 32, 78]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

# Where function

In [11]:
# where function is used to indicate array position

In [12]:
import numpy as np
ar1=np.array([23,34,45,32,44,12,32,55,67])
print(ar1)
ap=np.where(ar1==32)
print(ap)

[23 34 45 32 44 12 32 55 67]
(array([3, 6], dtype=int64),)


In [13]:
import numpy as np
ar1=np.array([23,34,45,32,44,12,32,55,67])
print(ar1)
ap=np.where(ar1==34)
print(ap)

[23 34 45 32 44 12 32 55 67]
(array([1], dtype=int64),)


In [14]:
import numpy as np
ar2=np.array([22,23,24,25,62,72])
ap=np.where(ar2%2==0)                    ## Check even numbers array position ##
print(ap)

(array([0, 2, 4, 5], dtype=int64),)


In [15]:
import numpy as np
ar2=np.array([22,23,24,25,62,72])
ap=np.where(ar2%2==1)                   ## Check odd numbers array position ##
print(ap)

(array([1, 3], dtype=int64),)
